### ISSUE TITLE
Simplify possible inputs for structure function calculations

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/lsstseries#59]
The goal is to allow the user only to specify a list of measurements to get a reasonable structure-function.

-   Allow user not to specify input times - assume equidistant times between measurements
-   Allow user not to specify errors - compute assuming that errors are zeros
-   If the user supplies a single value for an error, assume that it is the same error that needs to be applied for all of the measurements
-   Allow user not to have to supply band or id of lightcurves (more broadly - it is possible to operate on user-specified array inputs )

**Comment by drewoldag** [comment]
Just to make the pieces easier for me to track, I'm going break this up into a few smaller PRs. But I'll associate this issue with each of them. 

- [ ] Allow user not to specify input times - assume equidistant times between measurements

- [ ] Allow user not to specify errors - compute assuming that errors are zeros

- [ ] If the user supplies a single value for an error, assume that it is the same error that needs to be applied for all of the measurements

- [ ] Allow user not to have to supply band or id of lightcurves (more broadly - it is possible to operate on user-specified array inputs )

**Comment by drewoldag** [comment]
After conversations with @nevencaplar and @dougbrn there will be some additional work necessary to accomplish the desired result here. Note that 2 PRs (#84 #87) were created to allow users to pass None and scalar values for time and error, but that doesn't actually satisfy the initial request. (Those PRs have been merged and can be used directly, but we can do better)

Neven described the ideal desired result as follows:

> If I was an user and did not know anything, I would assume that I can pass three lists, that the first one is time, second one is flux, third one is errors. If I pass only two, time and flux. If I pass only one, it is flux. Unfortunately, that is not how python thinks.

So to clarify, we should be able to use the function equally well in the following three ways:
`sf2(flux=list_of_flux)`
`sf2(flux=list_of_flux, time=list_of_time)`
`sf2(flux=list_of_flux, time=list_of_time, err=scalar_or_list_of_errors)`

Doug pointed out that the current implementation in `Ensemble` and `TimeSeries` doesn't permit the user to avoid specifying time, error, band, id, etc... Some reasonable set of additional flags or a refactor would be needed so that the user can do that. `TimeSeries` has the most straightforward way for a user to _not_ provide time or error, but to do so, it seems that you have to recreate the TimeSeries object without time or error values - not a very dynamic way of working, and doesn't make this easy.
