### ISSUE TITLE
Add possibility in structure function that objects have the same weight

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/lsstseries#61]
When working with an ensemble (many lightcurves) we do not want that one or few lightcurves over-contribute to the estimate of the structure function.

Add a possibility to sample for each lightcurve number of pairs that correspond to the number of pairs you are getting from the lightcurve with the smallest number of points.

For example; two lightcurves, one with N_1 = 10, N_2=100, where N_i is the number of points in each lightcurve. The first one gives 10*9/2 = 45 pairs, the second gives 100*99/2 = 4950 pairs. Sample 45 pairs from each lightcurve. I think this is better than sampling 10 points from each curve, even though it is potentially more expensive.

**Comment by drewoldag** [comment]
Notes for my future self. Numpy's np.random.choice(np.array, N, replace=False) seems like a useful tool for this work.

**Comment by drewoldag** [comment]
Notes from conversations: 

- Operating per band. Each band is essentially it's own object, so for instance N_1 with 100 r-band obs and 10 g-band obs, should not subsample the r-band.
- We should operate on pairs of values (i.e. the differences). Keep in mind that we'll also want to 'bootstrap' (resample multiple times as in issue #62) so it will be good to keep the original full set of pairs, so that we can quickly resample from it multiple times without having to recalculate it. 
- Keep an eye on memory/cpu usage. Estimating that we could get into the regime of several thousands of observations. Should investigate what the practical limits are.
